name = "Fossils 'n Fuels"
author = "Creatures5"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cdaadc16bc8136768713115197cee45955b313fee6b902f1b6fd7d2224d0de1"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
