name = "Fossils 'n Fuels"
author = "Creatures5"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6109a5192b08b69624ed6d30f2037045f2c68010857539e3cd928675cfa6bcf"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
