name = "Fossils 'n Fuels"
author = "Creatures5"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ec06dc10fb7cdad2f4b2c5f6f558347ad693e649be288fb97687cc00f68c73a"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
